name: Run Unit Tests After Build

on: [push]
  #push:
    #branches:
     # - assignment6  # Adjust branch name if needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Build Script
        run: ./build.sh  # Execute your build script

      # You can add additional steps here if needed
