name: Ali Unittest Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run Tests
        run: npm test
